run:
  timeout: 5m
  skip-dirs:
    - test
    - vendor

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - golint
    - misspell
    - prealloc

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/skylarhoughtongithub/gopokedex
  golint:
    min-confidence: 0.8

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - dupl